# Generated by Django 4.2.7 on 2024-01-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPlayer', models.CharField(max_length=25, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='NOMBRES')),
                ('apellido', models.CharField(max_length=50, verbose_name='APELLIDOS')),
                ('puntos', models.CharField(max_length=25, verbose_name='PUNTOS')),
                ('url', models.CharField(max_length=150, verbose_name='URL')),
                ('updated', models.CharField(max_length=50, verbose_name='ACTUALIZADO')),
                ('team', models.CharField(max_length=50, verbose_name='EQUIPO')),
                ('desc', models.CharField(max_length=50, verbose_name='DESCRIPCION')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
